#!/usr/bin/env python
# coding: utf-8

import sys
import re
import itertools

budget = sys.stdin.read()

for line in budget.split('\n'):
    cells = list(c.strip() for c in line.split('\t'))

    # Ignore lines with only empty cells
    if not reduce(lambda t, c: t or bool(c), cells):
        continue

    if cells[0] == '':
        cells[0] = r'\hspace*{1em}'

    if cells[1] == '':
        cells[1] = r'\hspace*{1em}'

    if cells[0] in ('Sum', 'Expenses'):
        budget += r'[0.5ex]'

    if cells[0] == 'Sum':
        budget += r'\hline'
        cells[0] = r'\bf Sum'

    def format_euro(e):
        e = re.sub(r'([0-9,.]*)[.,]([0-9]{2})\s*€', r'\1:\2', e)
        e = e.replace('.', '')
        e = e.replace(',', '')
        e = e.replace(':', '.')
        try:
            e = '%0.2f' % float(e)
        except:
            e = '{%s}' % e

        return e


    cells[3:] = [format_euro(c) for c in cells[3:]]

    budget += '\n' + ' '.join(cells[0:3]) + ' & ' + ' & '.join(cells[3:]) + r'\\'

print budget

